<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Top-Ten" data-toc-modified-id="Top-Ten-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Top Ten</a></span></li><li><span><a href="#Popular-Top-Ten" data-toc-modified-id="Popular-Top-Ten-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Popular Top Ten</a></span></li><li><span><a href="#GenreCount" data-toc-modified-id="GenreCount-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>GenreCount</a></span></li><li><span><a href="#Documentary-Galore" data-toc-modified-id="Documentary-Galore-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Documentary Galore</a></span></li><li><span><a href="#Top-Three-Per-Genre" data-toc-modified-id="Top-Three-Per-Genre-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Top Three Per Genre</a></span></li><li><span><a href="#Genre-Averages" data-toc-modified-id="Genre-Averages-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Genre Averages</a></span></li><li><span><a href="#Romantic-Comedy-by-Decades" data-toc-modified-id="Romantic-Comedy-by-Decades-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Romantic Comedy by Decades</a></span></li></ul></div>

# International Movie Database

Data o 58,786 filmech do roku 2005.

In [1]:
df_imdb <- read.table('imdb.csv', sep=';', header = T)
head(df_imdb)

  var1 title                    year length budget rating votes r1   r2   r3
1 1    $                        1971 121    NA     6.4    348    4.5  4.5 4.5
2 2    $1000 a Touchdown        1939  71    NA     6.0     20    0.0 14.5 4.5
3 3    $21 a Day Once a Month   1941   7    NA     8.2      5    0.0  0.0 0.0
4 4    40000                    1996  70    NA     8.2      6   14.5  0.0 0.0
5 5    $50,000 Climax Show, The 1975  71    NA     3.4     17   24.5  4.5 0.0
6 6    $pent                    2000  91    NA     4.3     45    4.5  4.5 4.5
  ... r9   r10  mpaa Action Animation Comedy Drama Documentary Romance Short
1 ...  4.5  4.5      0      0         1      1     0           0       0
2 ...  4.5 14.5      0      0         1      0     0           0       0
3 ... 24.5 24.5      0      1         0      0     0           0       1
4 ... 34.5 45.5      0      0         1      0     0           0       0
5 ...  0.0 24.5      0      0         0      0     0           0       0
6 ... 14.5 14.5      0      0         0      1     0           0       0

In [2]:
df_imdb$var1 <- NULL

## Top Ten

Zobrazte deset nejlépe hodnocených filmů (sloupec `rating`).

In [3]:
head(
    df_imdb[order(df_imdb$rating, decreasing = T),]
    , 10
)

      title                                   year length budget rating votes
13907 Dimensia Minds Trilogy: The Hope Factor 2004 10       NA   10.0    5
18015 Fishing for Love                        2001  7       NA   10.0    5
49844 Summer Sonata, A                        2004 30     2000   10.0    5
5898  Black Canyon                            2004 25     3000    9.9    9
7711  Buck Privates                           1928 70       NA    9.9    7
13170 Defilada                                1989 60       NA    9.9    8
13908 Dimensia Minds Trilogy: The Reds        2004  8     1200    9.9   15
15018 Drifting                                2004 21     3000    9.9   41
15658 Ekdromi, I                              1966 85       NA    9.9    7
19825 Genet parle d'Angela Davis              1970 10       NA    9.9    7
      r1 r2  r3  r4 ... r9   r10   mpaa Action Animation Comedy Drama
13907 0  0.0 0.0 0  ...  0.0 100.0      0      0         0      0
18015 0  0.0 0.0 0  ...  0.0 100.0      0      0         1      0
49844 0  0.0 0.0 0  ...  0.0 100.0      0      0         0      1
5898  0  0.0 0.0 0  ... 14.5  84.5      0      0         0      0
7711  0  0.0 0.0 0  ... 14.5  84.5      0      0         1      0
13170 0  0.0 0.0 0  ... 14.5  84.5      0      0         0      0
13908 0  0.0 0.0 0  ... 14.5  84.5      0      0         0      0
15018 0  4.5 4.5 0  ...  0.0  94.5      0      0         0      1
15658 0  0.0 0.0 0  ... 14.5  84.5      0      0         0      1
19825 0  0.0 0.0 0  ... 24.5  74.5      0      0         0      0
      Documentary Romance Short
13907 0           0       1
18015 0           0       1
49844 0           0       1
5898  0           0       1
7711  0           0       0
13170 1           0       0
13908 0           0       1
15018 0           0       1
15658 0           1       0
19825 0           0       1

## Popular Top Ten

Zobrazte deset nejlépe hodnocených filmů, které mají alespoň 5000 hodnocení (sloupec `votes`).

In [4]:
mask <- df_imdb$votes >= 5000
df_imdb_popular <- df_imdb[mask,]

head(
    df_imdb_popular[order(df_imdb_popular$rating, decreasing = T),]
    , 10
)

      title                                              year length budget
20544 Godfather, The                                     1972 175     6000000
46267 Shawshank Redemption, The                          1994 142    25000000
30657 Lord of the Rings: The Return of the King, The     2003 251    94000000
20545 Godfather: Part II, The                            1974 200    13000000
46406 Shichinin no samurai                               1954 206      500000
7897  Buono, il brutto, il cattivo, Il                   1966 180     1200000
8882  Casablanca                                         1942 102      950000
30656 Lord of the Rings: The Fellowship of the Ring, The 2001 208    93000000
30658 Lord of the Rings: The Two Towers, The             2002 223    94000000
41660 Pulp Fiction                                       1994 168     8000000
      rating votes  r1  r2  r3  r4  ... r9   r10  mpaa  Action Animation Comedy
20544 9.1    122755 4.5 4.5 4.5 4.5 ... 14.5 45.5       0      0         0
46267 9.1    149494 4.5 4.5 4.5 4.5 ... 24.5 45.5 R     0      0         0
30657 9.0    103631 4.5 4.5 4.5 4.5 ... 14.5 64.5 PG-13 1      0         0
20545 8.9     71363 4.5 4.5 4.5 4.5 ... 24.5 44.5       0      0         0
46406 8.9     32141 4.5 4.5 4.5 4.5 ... 14.5 45.5       1      0         0
7897  8.8     30224 4.5 4.5 4.5 4.5 ... 24.5 44.5       1      0         0
8882  8.8     66030 4.5 4.5 4.5 4.5 ... 24.5 44.5       0      0         0
30656 8.8    157608 4.5 4.5 4.5 4.5 ... 14.5 45.5 PG-13 1      0         0
30658 8.8    114797 4.5 4.5 4.5 4.5 ... 24.5 44.5 PG-13 1      0         0
41660 8.8    132745 4.5 4.5 4.5 4.5 ... 24.5 44.5 R     0      0         0
      Drama Documentary Romance Short
20544 1     0           0       0
46267 1     0           0       0
30657 0     0           0       0
20545 1     0           0       0
46406 1     0           0       0
7897  1     0           0       0
8882  1     0           1       0
30656 0     0           0       0
30658 0     0           0       0
41660 1     0           0       0

## GenreCount

Přidejte do tabulky nový sloupec `GenreCount`, který bude označovat, do kolika žánrů najednou film patří.

In [5]:
genres <- c(
    'Short', 
    'Romance', 
    'Documentary', 
    'Drama', 
    'Comedy', 
    'Animation', 
    'Action'
)

In [6]:
# rychle s vyuzitim jen latky z tutorialu

ptm <- proc.time()

genre_count <- rep(0, nrow(df_imdb))
for (genre in genres) {
    genre_count <- genre_count + df_imdb[[genre]]
}
df_imdb[['GenreCount']] <- genre_count

print(proc.time() - ptm)

head(df_imdb)

   user  system elapsed
  0.005   0.001   0.006

  title                    year length budget rating votes r1   r2   r3  r4
1 $                        1971 121    NA     6.4    348    4.5  4.5 4.5  4.5
2 $1000 a Touchdown        1939  71    NA     6.0     20    0.0 14.5 4.5 24.5
3 $21 a Day Once a Month   1941   7    NA     8.2      5    0.0  0.0 0.0  0.0
4 40000                    1996  70    NA     8.2      6   14.5  0.0 0.0  0.0
5 $50,000 Climax Show, The 1975  71    NA     3.4     17   24.5  4.5 0.0 14.5
6 $pent                    2000  91    NA     4.3     45    4.5  4.5 4.5 14.5
  ... r10  mpaa Action Animation Comedy Drama Documentary Romance Short
1 ...  4.5      0      0         1      1     0           0       0
2 ... 14.5      0      0         1      0     0           0       0
3 ... 24.5      0      1         0      0     0           0       1
4 ... 45.5      0      0         1      0     0           0       0
5 ... 24.5      0      0         0      0     0           0       0
6 ... 14.5      0      0         0      1     0           0       0
  GenreCount
1 2
2 1
3 2
4 1
5 0
6 1

In [7]:
# nebo o fous rychlejsi podle Katky Liskove pomoci funkce rowSums

ptm <- proc.time()

df_imdb["GenreCount"] <- rowSums(df_imdb[genres])

print(proc.time() - ptm)

head(df_imdb)

   user  system elapsed
  0.004   0.000   0.004

  title                    year length budget rating votes r1   r2   r3  r4
1 $                        1971 121    NA     6.4    348    4.5  4.5 4.5  4.5
2 $1000 a Touchdown        1939  71    NA     6.0     20    0.0 14.5 4.5 24.5
3 $21 a Day Once a Month   1941   7    NA     8.2      5    0.0  0.0 0.0  0.0
4 40000                    1996  70    NA     8.2      6   14.5  0.0 0.0  0.0
5 $50,000 Climax Show, The 1975  71    NA     3.4     17   24.5  4.5 0.0 14.5
6 $pent                    2000  91    NA     4.3     45    4.5  4.5 4.5 14.5
  ... r10  mpaa Action Animation Comedy Drama Documentary Romance Short
1 ...  4.5      0      0         1      1     0           0       0
2 ... 14.5      0      0         1      0     0           0       0
3 ... 24.5      0      1         0      0     0           0       1
4 ... 45.5      0      0         1      0     0           0       0
5 ... 24.5      0      0         0      0     0           0       0
6 ... 14.5      0      0         0      1     0           0       0
  GenreCount
1 2
2 1
3 2
4 1
5 0
6 1

In [8]:
# mozne i reseni pomoci apply ale je trochu pomalejsi

ptm <- proc.time()

df_imdb[['GenreCount']] <- apply(
    df_imdb[genres],
    1,
    sum 
)

print(proc.time() - ptm)
                                 
head(df_imdb)

   user  system elapsed
  0.075   0.000   0.075

  title                    year length budget rating votes r1   r2   r3  r4
1 $                        1971 121    NA     6.4    348    4.5  4.5 4.5  4.5
2 $1000 a Touchdown        1939  71    NA     6.0     20    0.0 14.5 4.5 24.5
3 $21 a Day Once a Month   1941   7    NA     8.2      5    0.0  0.0 0.0  0.0
4 40000                    1996  70    NA     8.2      6   14.5  0.0 0.0  0.0
5 $50,000 Climax Show, The 1975  71    NA     3.4     17   24.5  4.5 0.0 14.5
6 $pent                    2000  91    NA     4.3     45    4.5  4.5 4.5 14.5
  ... r10  mpaa Action Animation Comedy Drama Documentary Romance Short
1 ...  4.5      0      0         1      1     0           0       0
2 ... 14.5      0      0         1      0     0           0       0
3 ... 24.5      0      1         0      0     0           0       1
4 ... 45.5      0      0         1      0     0           0       0
5 ... 24.5      0      0         0      0     0           0       0
6 ... 14.5      0      0         0      1     0           0       0
  GenreCount
1 2
2 1
3 2
4 1
5 0
6 1

In [9]:
# takhle spis ne 
# (cykly jsou vetsinou extremne pomale pro vetsi data)

ptm <- proc.time()

for (row_idx in 1:nrow(df_imdb)) {
    df_imdb[row_idx,'GenreCount'] <- sum(df_imdb[row_idx,genres])
}

print(proc.time() - ptm)

head(df_imdb)

   user  system elapsed
 11.297   0.017  11.314

  title                    year length budget rating votes r1   r2   r3  r4
1 $                        1971 121    NA     6.4    348    4.5  4.5 4.5  4.5
2 $1000 a Touchdown        1939  71    NA     6.0     20    0.0 14.5 4.5 24.5
3 $21 a Day Once a Month   1941   7    NA     8.2      5    0.0  0.0 0.0  0.0
4 40000                    1996  70    NA     8.2      6   14.5  0.0 0.0  0.0
5 $50,000 Climax Show, The 1975  71    NA     3.4     17   24.5  4.5 0.0 14.5
6 $pent                    2000  91    NA     4.3     45    4.5  4.5 4.5 14.5
  ... r10  mpaa Action Animation Comedy Drama Documentary Romance Short
1 ...  4.5      0      0         1      1     0           0       0
2 ... 14.5      0      0         1      0     0           0       0
3 ... 24.5      0      1         0      0     0           0       1
4 ... 45.5      0      0         1      0     0           0       0
5 ... 24.5      0      0         0      0     0           0       0
6 ... 14.5      0      0         0      1     0           0       0
  GenreCount
1 2
2 1
3 2
4 1
5 0
6 1

## Documentary Galore

Ve kterém roce se natočilo nejvíce dokumentárních filmů? Kolik jich bylo? 

Na závěr zkuste ještě nějak přehledně v jedné tabulce zobrazit informaci o natočených filmech všech žánrů pro každý rok.

In [10]:
# usetri cas v prikladech nize
df_imdb_docs <- df_imdb[df_imdb$Documentary == 1,]

In [11]:
dim(df_imdb)

[1] 58786    25

In [12]:
dim(df_imdb_docs)

[1] 3472   25

In [13]:
# citelne a rychle podle tapply

ptm <- proc.time()

df_imdb_docs <- df_imdb[df_imdb$Documentary == 1,]
counts <- tapply(
    df_imdb_docs$Documentary,
    df_imdb_docs$year,    
    length
)

sort(counts, decreasing = T)[1]

print(proc.time() - ptm)

2003
 261

   user  system elapsed
  0.008   0.000   0.008

In [14]:
# kreativni a velice rychle reseni podle Lucky Cervenkove (jen mene citelne)

ptm <- proc.time()

sort(summary(as.factor(df_imdb_docs$year)), decreasing = T)[1] 

print(proc.time() - ptm)

2003
 261

   user  system elapsed
  0.004   0.000   0.004

In [15]:
summary(as.factor(df_imdb_docs$year))

   2003    2004    2002    2001    2000    1999    1997    1998    1996    1994
    261     258     249     196     175     156     133     133      98      94
   1995    1992    1993    1987    1991    1984    1985    1988    1990    1971
     84      74      60      49      46      45      45      42      41      40
   1982    1978    1967    1976    1968    1989    1975    2005    1980    1970
     40      39      38      38      37      37      36      35      33      32
   1972    1981    1983    1986    1965    1974    1979    1943    1973    1977
     31      31      31      31      29      27      27      26      24      24
   1945    1969    1964    1966    1942    1963    1956    1940    1941    1955
     22      22      21      20      19      19      17      16      16      15
   1944    1935    1951    1953    1957    1959    1960    1946    1948    1952
     14      13      13      13      13      13      13      12      12      12
   1954    1961    1929    1938    1950    1962    1937    1939    1958    1901
     12      12      11      11      11      11      10      10      10       9
   1949    1903    1896    1930    1933    1934    1947    1897    1932    1894
      9       8       7       7       7       7       7       6       6       5
   1900    1931    1899    1904    1906    1928    1936    1895    1902    1905
      5       5       4       4       4       4       4       2       2       2
   1910    1919    1923    1925    1926    1927    1898    1908    1911 (Other)
      2       2       2       2       2       2       1       1       1       5

In [16]:
# table se da take pouzit, ale je to trochu pomalejsi

ptm <- proc.time()

sort(table(df_imdb$year, df_imdb$Documentary)[,2], decreasing = T)[1]

print(proc.time() - ptm)

2003
 261

   user  system elapsed
  0.017   0.000   0.017

In [17]:
table(df_imdb$year, df_imdb$Documentary)

          0    1
  1893    1    0
  1894    4    5
  1895    1    2
  1896    6    7
  1897    3    6
  1898    4    1
  1899    5    4
  1900   11    5
  1901   19    9
  1902    7    2
  1903   29    8
  1904   38    4
  1905   15    2
  1906   13    4
  1907   12    0
  1908   23    1
  1909   30    0
  1910   24    2
  1911   21    1
  1912   34    0
  1913   31    1
  1914   53    1
  1915   53    1
  1916   49    0
  1917   37    0
  1918   40    1
  1919   50    2
  1920   43    0
  1921   53    0
  1922   51    1
  1923   46    2
  1924   50    0
  1925   77    2
  1926   92    2
  1927   81    2
  1928  105    4
  1929  173   11
  1930  281    7
  1931  341    5
  1932  406    6
  1933  414    7
  1934  475    7
  1935  451   13
  1936  480    4
  1937  474   10
  1938  452   11
  1939  474   10
  1940  487   16
  1941  505   16
  1942  488   19
  1943  420   26
  1944  412   14
  1945  353   22
  1946  420   12
  1947  432    7
  1948  466   12
  1949  477    9
  1950  480   11
  1951  505   13
  1952  501   12
  1953  526   13
  1954  489   12
  1955  507   15
  1956  480   17
  1957  543   13
  1958  518   10
  1959  482   13
  1960  465   13
  1961  454   12
  1962  502   11
  1963  484   19
  1964  496   21
  1965  501   29
  1966  559   20
  1967  556   38
  1968  614   37
  1969  603   22
  1970  553   32
  1971  606   40
  1972  606   31
  1973  610   24
  1974  598   27
  1975  583   36
  1976  627   38
  1977  593   24
  1978  570   39
  1979  605   27
  1980  648   33
  1981  630   31
  1982  649   40
  1983  667   31
  1984  704   45
  1985  747   45
  1986  761   31
  1987  907   49
  1988  902   42
  1989  907   37
  1990  858   41
  1991  842   46
  1992  874   74
  1993  956   60
  1994 1105   94
  1995 1164   84
  1996 1292   98
  1997 1435  133
  1998 1572  133
  1999 1771  156
  2000 1873  175
  2001 1925  196
  2002 1919  249
  2003 1897  261
  2004 1687  258
  2005  314   35

In [18]:
# i by funguje, ale zase trochu pomaleji

ptm <- proc.time()

movies_by_year <- by(
    df_imdb,
    df_imdb$year,
    function(group, genre) {
        return(sum(group[,genre]))
    },
    'Documentary'
)

print(proc.time() - ptm)

best_year <- movies_by_year[movies_by_year == max(movies_by_year)]

print(proc.time() - ptm)

best_year

   user  system elapsed
  0.039   0.000   0.039
   user  system elapsed
  0.041   0.000   0.042

2003
 261

In [19]:
# mozno i takto, ale kvuli komplexnejsimu by je to zrejme jeste pomalejsi

ptm <- proc.time()

movies_by_year <- by(
    df_imdb,
    list(
        df_imdb$year,
        df_imdb$Documentary
    ),
    function(group, genre) {
        return(sum(group[,'Documentary']))
    }
)

print(proc.time() - ptm)

best_year <- sort(rbind(movies_by_year)[,2], decreasing = T)

print(proc.time() - ptm)

best_year[1]

   user  system elapsed
  0.054   0.000   0.054
   user  system elapsed
  0.056   0.000   0.056

2003
 261

In [20]:
# aggregate nam muze dat prehledne dohromady tabulku pro vsechny zanry

genre_stats <- aggregate(
    df_imdb[genres],
    list(year=df_imdb$year),
    sum
)

head(genre_stats[order(genre_stats$year, decreasing = T),])

    year Short Romance Documentary Drama Comedy Animation Action
113 2005  54    37      35         137   123    10         43
112 2004 480   169     258         805   597    56        147
111 2003 555   215     261         899   642    94        180
110 2002 533   245     249         929   591    81        176
109 2001 468   211     196         837   582    82        169
108 2000 449   207     175         793   561    89        154

In [21]:
# takze se muzeme snadno podivat, jak to s nimi bude

genre <- 'Documentary'
head(
    genre_stats[
        order(genre_stats[[genre]], decreasing = T),
        c('year', genre)
    ]
)

    year Documentary
111 2003 261
112 2004 258
110 2002 249
109 2001 196
108 2000 175
107 1999 156

## Top Three Per Genre

Zobrazte tři nejlépe hodnocené filmy pro každý žánr. Uložte jako seznam (`list`), kde klíč je název žánru a hodnota je vektor jmen těchto filmů.

**Bonus:** Omezte se pouze na filmy s alespoň 5,000 hodnoceními (`votes`) a přidejte jejich hodnocení (`rating`) do výstupu, který teď bude seznam (`list`) objektů `data.frame`.

In [22]:
best_of_genres <- list()
for (genre in genres) {
    mask <- df_imdb[[genre]] == 1
    genre_subset <- df_imdb[mask,]
    best_of_genres[[genre]] <- as.vector(
        genre_subset[order(genre_subset$rating, decreasing = T),'title'][1:3]
    )
}
best_of_genres

$Short
[1] "Dimensia Minds Trilogy: The Hope Factor"
[2] "Fishing for Love"
[3] "Summer Sonata, A"

$Romance
[1] "Ekdromi, I"        "Tosca"             "Distinto amanecer"

$Documentary
[1] "Defilada"          "Clown"             "Drive-by Shooting"

$Drama
[1] "Summer Sonata, A" "Drifting"         "Ekdromi, I"

$Comedy
[1] "Fishing for Love" "Buck Privates"    "Penis Envy"

$Animation
[1] "Milton Is a Shitbag"         "Mumi-troll i drugie"
[3] "Self Defense... for Cowards"

$Action
[1] "Clase z tropical" "Goodnite Charlie" "Leng mian hu"

In [23]:
# bonus

est_of_genres <- list()
for (genre in genres) {
    mask <- df_imdb[[genre]] == 1 & df_imdb$votes > 5000
    genre_subset <- df_imdb[mask,]
    best_of_genres[[genre]] <- genre_subset[order(genre_subset$rating, decreasing = T),c('title', 'rating')][1:3,]
}
best_of_genres

$Short
                                     title rating
55998 Wallace & Gromit: The Wrong Trousers    8.4
55995      Wallace & Gromit: A Close Shave    8.2
55996    Wallace & Gromit: A Grand Day Out    7.7

$Romance
                                      title rating
8882                             Casablanca    8.8
16423 Eternal Sunshine of the Spotless Mind    8.6
25961                 It's a Wonderful Life    8.6

$Documentary
                      title rating
7104  Bowling for Columbine    8.5
16894       Fahrenheit 9/11    7.9
43740            Roger & Me    7.7

$Drama
                          title rating
20544            Godfather, The    9.1
46267 Shawshank Redemption, The    9.1
20545   Godfather: Part II, The    8.9

$Comedy
                                                                     title
14857 Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb
16423                                Eternal Sunshine of the Spotless Mind
7104                                                 Bowling for Columbine
      rating
14857    8.7
16423    8.6
7104     8.5

$Animation
                                     title rating
45695        Sen to Chihiro no kamikakushi    8.6
55998 Wallace & Gromit: The Wrong Trousers    8.4
17842                         Finding Nemo    8.3

$Action
                                               title rating
30657 Lord of the Rings: The Return of the King, The    9.0
46406                           Shichinin no samurai    8.9
7897                Buono, il brutto, il cattivo, Il    8.8

## Genre Averages

Spočítejte průměrná hodnocení filmů v jednotlivých žánrech. Jsou komedie v průměru lépe hodnocené než akční filmy? Zkusíte navrhnout a provést statistický test?

In [24]:
ptm <- proc.time()

genre_averages <- list()
for (genre in genres) {
    mask <- df_imdb[[genre]] == 1
    genre_subset <- df_imdb[mask,]
    genre_averages[[genre]] <- round(mean(genre_subset$rating), 2)
}

print(proc.time() - ptm)

genre_averages

   user  system elapsed
  0.041   0.000   0.042

$Short
[1] 6.48

$Romance
[1] 6.16

$Documentary
[1] 6.65

$Drama
[1] 6.15

$Comedy
[1] 5.96

$Animation
[1] 6.58

$Action
[1] 5.29

In [25]:
ptm <- proc.time()

genre_averages <- as.list(apply(
    df_imdb[genres],
    2,
    function (genre_col) {
        mean(df_imdb[genre_col == 1,]$rating)
    }
))

print(proc.time() - ptm)

genre_averages

   user  system elapsed
  0.048   0.000   0.048

$Short
[1] 6.481423

$Romance
[1] 6.163997

$Documentary
[1] 6.650576

$Drama
[1] 6.153684

$Comedy
[1] 5.955492

$Animation
[1] 6.583686

$Action
[1] 5.292022

In [26]:
genre_averages$Comedy > genre_averages$Action

[1] TRUE

In [27]:
genre_data <- list()
for (genre in genres) {
    mask <- df_imdb[[genre]] == 1
    genre_data[[genre]] <- df_imdb[mask,]$rating
}
t.test(genre_data$Comedy, genre_data$Action, alternative = c('greater'))

	Welch Two Sample t-test

data:  genre_data$Comedy and genre_data$Action
t = 26.125, df = 7043.7, p-value < 2.2e-16
alternative hypothesis: true difference in means is greater than 0
95 percent confidence interval:
 0.6216911       Inf
sample estimates:
mean of x mean of y
 5.955492  5.292022

## Romantic Comedy by Decades

Najděte tři nejlepší romantické komedie z každého desetiletí. Filmy v konečném pořadí musí mít alespoň 30 hodnocení.

**Bonus:** Upravte svůj kód tak, aby se dal aplikovat na jakýkoliv žánr (nebo mix žánrů). Vytvořte si funkci s patřičnými parametry.

In [28]:
ptm <- proc.time()

df_imdb['decade'] <- df_imdb$year - df_imdb$year %% 10
best_romcoms <- by(
    df_imdb,
    df_imdb$decade,
    function(imdb_decade) {
        mask <- imdb_decade$Comedy == 1 & imdb_decade$Romance == 1 & imdb_decade$votes >= 30
        romcoms <- imdb_decade[mask,]
        rating_order <- order(romcoms$rating, decreasing = T)
        return(romcoms[rating_order,][1:3,])
    }
)

print(proc.time() - ptm)

best_romcoms[names(best_romcoms)]

   user  system elapsed
  0.076   0.000   0.077

$`1890`
     title year length budget rating votes r1 r2 r3 r4 r5 r6 r7 r8 r9 r10 mpaa
NA    <NA>   NA     NA     NA     NA    NA NA NA NA NA NA NA NA NA NA  NA <NA>
NA.1  <NA>   NA     NA     NA     NA    NA NA NA NA NA NA NA NA NA NA  NA <NA>
NA.2  <NA>   NA     NA     NA     NA    NA NA NA NA NA NA NA NA NA NA  NA <NA>
     Action Animation Comedy Drama Documentary Romance Short GenreCount decade
NA       NA        NA     NA    NA          NA      NA    NA         NA     NA
NA.1     NA        NA     NA    NA          NA      NA    NA         NA     NA
NA.2     NA        NA     NA    NA          NA      NA    NA         NA     NA

$`1900`
     title year length budget rating votes r1 r2 r3 r4 r5 r6 r7 r8 r9 r10 mpaa
NA    <NA>   NA     NA     NA     NA    NA NA NA NA NA NA NA NA NA NA  NA <NA>
NA.1  <NA>   NA     NA     NA     NA    NA NA NA NA NA NA NA NA NA NA  NA <NA>
NA.2  <NA>   NA     NA     NA     NA    NA NA NA NA NA NA NA NA NA NA  NA <NA>
     Action Animation Comedy Drama Documentary Romance Short GenreCount decade
NA       NA        NA     NA    NA          NA      NA    NA         NA     NA
NA.1     NA        NA     NA    NA          NA      NA    NA         NA     NA
NA.2     NA        NA     NA    NA          NA      NA    NA         NA     NA

$`1910`
     title year length budget rating votes r1 r2 r3 r4 r5 r6 r7 r8 r9 r10 mpaa
NA    <NA>   NA     NA     NA     NA    NA NA NA NA NA NA NA NA NA NA  NA <NA>
NA.1  <NA>   NA     NA     NA     NA    NA NA NA NA NA NA NA NA NA NA  NA <NA>
NA.2  <NA>   NA     NA     NA     NA    NA NA NA NA NA NA NA NA NA NA  NA <NA>
     Action Animation Comedy Drama Documentary Romance Short GenreCount decade
NA       NA        NA     NA    NA          NA      NA    NA         NA     NA
NA.1     NA        NA     NA    NA          NA      NA    NA         NA     NA
NA.2     NA        NA     NA    NA          NA      NA    NA         NA     NA

$`1920`
                 title year length budget rating votes  r1  r2  r3  r4  r5  r6
19809     General, The 1927     83     NA    8.4  6644 4.5 4.5 4.5 4.5 4.5 4.5
27646 Kid Brother, The 1927     84     NA    8.3   285 4.5 4.5 4.5 4.5 4.5 4.5
44422     Safety Last! 1923     70     NA    8.2   757 4.5 4.5 4.5 4.5 4.5 4.5
        r7   r8   r9  r10 mpaa Action Animation Comedy Drama Documentary
19809  4.5 14.5 24.5 34.5           1         0      1     0           0
27646 14.5 14.5 24.5 44.5           0         0      1     0           0
44422 14.5 24.5 24.5 34.5           1         0      1     0           0
      Romance Short GenreCount decade
19809       1     0          3   1920
27646       1     0          2   1920
44422       1     0          3   1920

$`1930`
                      title year length  budget rating votes  r1  r2  r3  r4
10228           City Lights 1931     87 1500000    8.5  7802 4.5 4.5 4.5 4.5
25871 It Happened One Night 1934    105  325000    8.3  7924 4.5 4.5 4.5 4.5
7493       Bringing Up Baby 1938    102      NA    8.2  9250 4.5 4.5 4.5 4.5
       r5  r6   r7   r8   r9  r10 mpaa Action Animation Comedy Drama
10228 4.5 4.5  4.5 14.5 24.5 44.5           0         0      1     1
25871 4.5 4.5 14.5 24.5 24.5 34.5           0         0      1     0
7493  4.5 4.5 14.5 24.5 24.5 34.5           0         0      1     0
      Documentary Romance Short GenreCount decade
10228           0       1     0          3   1930
25871           0       1     0          2   1930
7493            0       1     0          2   1930

$`1940`
                title year length budget rating votes  r1  r2  r3  r4  r5   r6
15948       Enamorada 1946     99     NA    8.4    49 0.0 0.0 0.0 0.0 4.5  4.5
17753 Film ohne Titel 1948     99     NA    8.2    38 0.0 0.0 0.0 0.0 0.0 14.5
23171 His Girl Friday 1940     92     NA    8.2  6667 4.5 4.5 4.5 4.5 4.5  4.5
        r7   r8   r9  r10 mpaa Action Animation Comedy Drama Documentary
15948 14.5 24.5  4.5 45.5           0         0      1     1           0
17753 14.5 34.5 14.5 24.5           0         0      1     0           0
23171 14.5 24.5 24.5 24.5           0         0      1     1           0
      Romance Short GenreCount decade
15948       1     0          3   1940
17753       1     0          2   1940
23171       1     0          3   1940

$`1950`
                     title year length  budget rating votes  r1  r2  r3  r4  r5
14645 Dos tipos de cuidado 1953    123      NA    8.5    52 4.5 4.5 0.0 0.0 4.5
47033  Singin' in the Rain 1952    103 2540800    8.5 20585 4.5 4.5 4.5 4.5 4.5
47952     Some Like It Hot 1959    120 2883848    8.4 25369 4.5 4.5 4.5 4.5 4.5
       r6   r7   r8   r9  r10 mpaa Action Animation Comedy Drama Documentary
14645 4.5  4.5 24.5 14.5 44.5           0         0      1     0           0
47033 4.5 14.5 14.5 14.5 34.5           0         0      1     0           0
47952 4.5 14.5 24.5 24.5 34.5           0         0      1     0           0
      Romance Short GenreCount decade
14645       1     0          2   1950
47033       1     0          2   1950
47952       1     0          2   1950

$`1960`
                      title year length budget rating votes  r1 r2  r3  r4  r5
13598              Devchata 1961     98     NA    9.2    50 0.0  0 0.0 0.0 4.5
5139    Beregis avtomobilya 1966     94     NA    9.0   241 4.5  0 4.5 4.5 4.5
44445 Sahib Bibi Aur Ghulam 1962    152     NA    9.0    76 4.5  0 4.5 4.5 0.0
       r6  r7   r8   r9  r10 mpaa Action Animation Comedy Drama Documentary
13598 4.5 4.5 14.5 14.5 64.5           0         0      1     0           0
5139  4.5 4.5 14.5 14.5 64.5           0         0      1     0           0
44445 4.5 4.5  4.5  4.5 74.5           0         0      1     1           0
      Romance Short GenreCount decade
13598       1     0          2   1960
5139        1     0          2   1960
44445       1     0          3   1960

$`1970`
                 title year length  budget rating votes  r1  r2  r3  r4  r5  r6
47498 Sluzhebnyy roman 1977    159      NA    9.1   320 4.5 4.5 4.5 4.5 4.5 4.5
2728        Annie Hall 1977     93 4000000    8.3 21462 4.5 4.5 4.5 4.5 4.5 4.5
46570             Shor 1972    170      NA    8.3    35 0.0 0.0 0.0 0.0 0.0 0.0
        r7   r8   r9  r10 mpaa Action Animation Comedy Drama Documentary
47498  4.5  4.5 14.5 64.5           0         0      1     0           0
2728  14.5 14.5 24.5 34.5           0         0      1     0           0
46570  4.5 24.5 45.5 14.5           0         0      1     1           0
      Romance Short GenreCount decade
47498       1     0          2   1970
2728        1     0          2   1970
46570       1     0          3   1970

$`1980`
                    title year length   budget rating votes  r1  r2  r3  r4  r5
9510      Chashme Buddoor 1981    145       NA    8.5    40 0.0 0.0 0.0 0.0 4.5
28551              Kuryer 1987     90       NA    8.2    88 0.0 0.0 0.0 4.5 4.5
41270 Princess Bride, The 1987     98 16000000    8.2 53946 4.5 4.5 4.5 4.5 4.5
       r6   r7   r8   r9  r10 mpaa Action Animation Comedy Drama Documentary
9510  4.5  4.5 24.5 24.5 44.5           0         0      1     0           0
28551 4.5 14.5 14.5 24.5 34.5           0         0      1     1           0
41270 4.5 14.5 14.5 24.5 34.5           0         0      1     0           0
      Romance Short GenreCount decade
9510        1     0          2   1980
28551       1     0          3   1980
41270       1     0          2   1980

$`1990`
                title year length budget rating votes  r1  r2  r3  r4  r5  r6
13305 Denei shoujo Ai 1992    180     NA    8.7   157 4.5 4.5 4.5 0.0 0.0 4.5
8102               C4 1996      4     NA    8.4    48 4.5 0.0 0.0 0.0 4.5 4.5
2277  Amor & Alquimia 1995     22     NA    8.1    36 0.0 0.0 0.0 4.5 4.5 0.0
        r7   r8   r9  r10 mpaa Action Animation Comedy Drama Documentary
13305 14.5 14.5 14.5 45.5           0         1      1     0           0
8102  14.5  4.5 74.5  4.5           0         0      1     0           0
2277   4.5 14.5  4.5 74.5           0         0      1     0           0
      Romance Short GenreCount decade
13305       1     0          3   1990
8102        1     1          3   1990
2277        1     1          3   1990

$`2000`
                                      title year length   budget rating votes
36420                      Night of the Dog 2005     86     5000    9.5    33
8890                 Casamento de Louise, O 2001     80       NA    8.8    40
16423 Eternal Sunshine of the Spotless Mind 2004    108 20000000    8.6 46240
       r1  r2  r3  r4  r5  r6   r7   r8   r9  r10 mpaa Action Animation Comedy
36420 4.5 0.0 4.5 0.0 0.0 0.0  4.5  4.5  4.5 84.5           0         0      1
8890  4.5 0.0 4.5 4.5 4.5 4.5 24.5  4.5 34.5 14.5           0         0      1
16423 4.5 4.5 4.5 4.5 4.5 4.5  4.5 14.5 24.5 44.5    R      0         0      1
      Drama Documentary Romance Short GenreCount decade
36420     0           0       1     0          2   2000
8890      0           0       1     0          2   2000
16423     1           0       1     0          3   2000

In [29]:
ptm <- proc.time()

mask <- df_imdb$Comedy == 1 & df_imdb$Romance == 1 & df_imdb$votes >= 30
romcoms <- df_imdb[mask,]
romcoms['decade'] <- romcoms$year - romcoms$year %% 10
best_romcoms <- by(
    romcoms,
    romcoms$decade,
    function(imdb_decade) {
        rating_order <- order(imdb_decade$rating, decreasing = T)
        return(imdb_decade[rating_order,][1:3,])
    }
)

print(proc.time() - ptm)

best_romcoms[names(best_romcoms)]

   user  system elapsed
  0.014   0.001   0.014

$`1920`
                 title year length budget rating votes  r1  r2  r3  r4  r5  r6
19809     General, The 1927     83     NA    8.4  6644 4.5 4.5 4.5 4.5 4.5 4.5
27646 Kid Brother, The 1927     84     NA    8.3   285 4.5 4.5 4.5 4.5 4.5 4.5
44422     Safety Last! 1923     70     NA    8.2   757 4.5 4.5 4.5 4.5 4.5 4.5
        r7   r8   r9  r10 mpaa Action Animation Comedy Drama Documentary
19809  4.5 14.5 24.5 34.5           1         0      1     0           0
27646 14.5 14.5 24.5 44.5           0         0      1     0           0
44422 14.5 24.5 24.5 34.5           1         0      1     0           0
      Romance Short GenreCount decade
19809       1     0          3   1920
27646       1     0          2   1920
44422       1     0          3   1920

$`1930`
                      title year length  budget rating votes  r1  r2  r3  r4
10228           City Lights 1931     87 1500000    8.5  7802 4.5 4.5 4.5 4.5
25871 It Happened One Night 1934    105  325000    8.3  7924 4.5 4.5 4.5 4.5
7493       Bringing Up Baby 1938    102      NA    8.2  9250 4.5 4.5 4.5 4.5
       r5  r6   r7   r8   r9  r10 mpaa Action Animation Comedy Drama
10228 4.5 4.5  4.5 14.5 24.5 44.5           0         0      1     1
25871 4.5 4.5 14.5 24.5 24.5 34.5           0         0      1     0
7493  4.5 4.5 14.5 24.5 24.5 34.5           0         0      1     0
      Documentary Romance Short GenreCount decade
10228           0       1     0          3   1930
25871           0       1     0          2   1930
7493            0       1     0          2   1930

$`1940`
                title year length budget rating votes  r1  r2  r3  r4  r5   r6
15948       Enamorada 1946     99     NA    8.4    49 0.0 0.0 0.0 0.0 4.5  4.5
17753 Film ohne Titel 1948     99     NA    8.2    38 0.0 0.0 0.0 0.0 0.0 14.5
23171 His Girl Friday 1940     92     NA    8.2  6667 4.5 4.5 4.5 4.5 4.5  4.5
        r7   r8   r9  r10 mpaa Action Animation Comedy Drama Documentary
15948 14.5 24.5  4.5 45.5           0         0      1     1           0
17753 14.5 34.5 14.5 24.5           0         0      1     0           0
23171 14.5 24.5 24.5 24.5           0         0      1     1           0
      Romance Short GenreCount decade
15948       1     0          3   1940
17753       1     0          2   1940
23171       1     0          3   1940

$`1950`
                     title year length  budget rating votes  r1  r2  r3  r4  r5
14645 Dos tipos de cuidado 1953    123      NA    8.5    52 4.5 4.5 0.0 0.0 4.5
47033  Singin' in the Rain 1952    103 2540800    8.5 20585 4.5 4.5 4.5 4.5 4.5
47952     Some Like It Hot 1959    120 2883848    8.4 25369 4.5 4.5 4.5 4.5 4.5
       r6   r7   r8   r9  r10 mpaa Action Animation Comedy Drama Documentary
14645 4.5  4.5 24.5 14.5 44.5           0         0      1     0           0
47033 4.5 14.5 14.5 14.5 34.5           0         0      1     0           0
47952 4.5 14.5 24.5 24.5 34.5           0         0      1     0           0
      Romance Short GenreCount decade
14645       1     0          2   1950
47033       1     0          2   1950
47952       1     0          2   1950

$`1960`
                      title year length budget rating votes  r1 r2  r3  r4  r5
13598              Devchata 1961     98     NA    9.2    50 0.0  0 0.0 0.0 4.5
5139    Beregis avtomobilya 1966     94     NA    9.0   241 4.5  0 4.5 4.5 4.5
44445 Sahib Bibi Aur Ghulam 1962    152     NA    9.0    76 4.5  0 4.5 4.5 0.0
       r6  r7   r8   r9  r10 mpaa Action Animation Comedy Drama Documentary
13598 4.5 4.5 14.5 14.5 64.5           0         0      1     0           0
5139  4.5 4.5 14.5 14.5 64.5           0         0      1     0           0
44445 4.5 4.5  4.5  4.5 74.5           0         0      1     1           0
      Romance Short GenreCount decade
13598       1     0          2   1960
5139        1     0          2   1960
44445       1     0          3   1960

$`1970`
                 title year length  budget rating votes  r1  r2  r3  r4  r5  r6
47498 Sluzhebnyy roman 1977    159      NA    9.1   320 4.5 4.5 4.5 4.5 4.5 4.5
2728        Annie Hall 1977     93 4000000    8.3 21462 4.5 4.5 4.5 4.5 4.5 4.5
46570             Shor 1972    170      NA    8.3    35 0.0 0.0 0.0 0.0 0.0 0.0
        r7   r8   r9  r10 mpaa Action Animation Comedy Drama Documentary
47498  4.5  4.5 14.5 64.5           0         0      1     0           0
2728  14.5 14.5 24.5 34.5           0         0      1     0           0
46570  4.5 24.5 45.5 14.5           0         0      1     1           0
      Romance Short GenreCount decade
47498       1     0          2   1970
2728        1     0          2   1970
46570       1     0          3   1970

$`1980`
                    title year length   budget rating votes  r1  r2  r3  r4  r5
9510      Chashme Buddoor 1981    145       NA    8.5    40 0.0 0.0 0.0 0.0 4.5
28551              Kuryer 1987     90       NA    8.2    88 0.0 0.0 0.0 4.5 4.5
41270 Princess Bride, The 1987     98 16000000    8.2 53946 4.5 4.5 4.5 4.5 4.5
       r6   r7   r8   r9  r10 mpaa Action Animation Comedy Drama Documentary
9510  4.5  4.5 24.5 24.5 44.5           0         0      1     0           0
28551 4.5 14.5 14.5 24.5 34.5           0         0      1     1           0
41270 4.5 14.5 14.5 24.5 34.5           0         0      1     0           0
      Romance Short GenreCount decade
9510        1     0          2   1980
28551       1     0          3   1980
41270       1     0          2   1980

$`1990`
                title year length budget rating votes  r1  r2  r3  r4  r5  r6
13305 Denei shoujo Ai 1992    180     NA    8.7   157 4.5 4.5 4.5 0.0 0.0 4.5
8102               C4 1996      4     NA    8.4    48 4.5 0.0 0.0 0.0 4.5 4.5
2277  Amor & Alquimia 1995     22     NA    8.1    36 0.0 0.0 0.0 4.5 4.5 0.0
        r7   r8   r9  r10 mpaa Action Animation Comedy Drama Documentary
13305 14.5 14.5 14.5 45.5           0         1      1     0           0
8102  14.5  4.5 74.5  4.5           0         0      1     0           0
2277   4.5 14.5  4.5 74.5           0         0      1     0           0
      Romance Short GenreCount decade
13305       1     0          3   1990
8102        1     1          3   1990
2277        1     1          3   1990

$`2000`
                                      title year length   budget rating votes
36420                      Night of the Dog 2005     86     5000    9.5    33
8890                 Casamento de Louise, O 2001     80       NA    8.8    40
16423 Eternal Sunshine of the Spotless Mind 2004    108 20000000    8.6 46240
       r1  r2  r3  r4  r5  r6   r7   r8   r9  r10 mpaa Action Animation Comedy
36420 4.5 0.0 4.5 0.0 0.0 0.0  4.5  4.5  4.5 84.5           0         0      1
8890  4.5 0.0 4.5 4.5 4.5 4.5 24.5  4.5 34.5 14.5           0         0      1
16423 4.5 4.5 4.5 4.5 4.5 4.5  4.5 14.5 24.5 44.5    R      0         0      1
      Drama Documentary Romance Short GenreCount decade
36420     0           0       1     0          2   2000
8890      0           0       1     0          2   2000
16423     1           0       1     0          3   2000

In [30]:
t(sapply(best_romcoms, function(x) paste(x$title, x$rating)))

     [,1]                     [,2]
1920 General, The 8.4         Kid Brother, The 8.3
1930 City Lights 8.5          It Happened One Night 8.3
1940 Enamorada 8.4            Film ohne Titel 8.2
1950 Dos tipos de cuidado 8.5 Singin' in the Rain 8.5
1960 Devchata 9.2             Beregis avtomobilya 9
1970 Sluzhebnyy roman 9.1     Annie Hall 8.3
1980 Chashme Buddoor 8.5      Kuryer 8.2
1990 Denei shoujo Ai 8.7      C4 8.4
2000 Night of the Dog 9.5     Casamento de Louise, O 8.8
     [,3]
1920 Safety Last! 8.2
1930 Bringing Up Baby 8.2
1940 His Girl Friday 8.2
1950 Some Like It Hot 8.4
1960 Sahib Bibi Aur Ghulam 9
1970 Shor 8.3
1980 Princess Bride, The 8.2
1990 Amor & Alquimia 8.1
2000 Eternal Sunshine of the Spotless Mind 8.6

In [31]:
get_best_movies_by_decade <- function (data, genres, top_max = 3, min_votes = 30, time_period = 10) {
    mask <- !logical(dim(data)[1])
    for (genre in genres) {
        mask <- mask & data[[genre]] == 1
    }
    data <- data[mask & data$votes >= min_votes,]
    data['decade'] <- data$year - data$year %% time_period
    
    best <- by(
        data,
        data$decade,
        function(imdb_decade) {
            rating_order <- order(imdb_decade$rating, decreasing = T)
            return(imdb_decade[rating_order,][1:top_max,])
        }
    )
    
    return(t(sapply(best, function(x) paste(x$title, x$rating))))
}

get_best_movies_by_decade(df_imdb, c('Romance', 'Comedy'), 3)

     [,1]                     [,2]
1920 General, The 8.4         Kid Brother, The 8.3
1930 City Lights 8.5          It Happened One Night 8.3
1940 Enamorada 8.4            Film ohne Titel 8.2
1950 Dos tipos de cuidado 8.5 Singin' in the Rain 8.5
1960 Devchata 9.2             Beregis avtomobilya 9
1970 Sluzhebnyy roman 9.1     Annie Hall 8.3
1980 Chashme Buddoor 8.5      Kuryer 8.2
1990 Denei shoujo Ai 8.7      C4 8.4
2000 Night of the Dog 9.5     Casamento de Louise, O 8.8
     [,3]
1920 Safety Last! 8.2
1930 Bringing Up Baby 8.2
1940 His Girl Friday 8.2
1950 Some Like It Hot 8.4
1960 Sahib Bibi Aur Ghulam 9
1970 Shor 8.3
1980 Princess Bride, The 8.2
1990 Amor & Alquimia 8.1
2000 Eternal Sunshine of the Spotless Mind 8.6

In [32]:
genres

[1] "Short"       "Romance"     "Documentary" "Drama"       "Comedy"
[6] "Animation"   "Action"

In [33]:
get_best_movies_by_decade(
    df_imdb, 
    c('Drama', 'Comedy'),
    5, 
    time_period = 5
)

     [,1]
1915 Daddy-Long-Legs 7
1920 Grenouilles qui demandent un roi, Les 8.2
1925 Cameraman, The 8
1930 City Lights 8.5
1935 Mr. Smith Goes to Washington 8.4
1940 To Be or Not to Be 8.3
1945 Enamorada 8.4
1950 African Queen, The 8.1
1955 Kalpiki lira 8.9
1960 Verdugo, El 9.1
1965 Caifanes, Los 8.7
1970 Sting, The 8.4
1975 Manhattan 8.2
1980 Hadashi no Gen 8.9
1985 Glissando 9.8
1990 Forrest Gump 8.2
1995 Neurosia - 50 Jahre pervers 9.5
2000 Cashback 9.8
2005 Bigger Than the Sky 7.3
     [,2]                                      [,3]
1915 Poor Little Rich Girl, The 6.9            NA NA
1920 Kid, The 8.2                              Bergkatze, Die 7.3
1925 Garden of Eden, The 7.9                   Patsy, The 7.9
1930 Fanny 8.3                                 Marius 8.1
1935 On Borrowed Time 8.1                      Holiday 7.7
1940 His Girl Friday 8.2                       Shop Around the Corner, The 8
1945 Kind Hearts and Coronets 8.2              Miracle on 34th Street 7.9
1950 Last Holiday 8.1                          Roman Holiday 8.1
1955 Grande guerra, La 8.7                     Kyojin to gangu 8.1
1960 Sahib Bibi Aur Ghulam 9                   Apartment, The 8.4
1965 Campanadas a medianoche 8.3               Graduate, The 8.2
1970 Beloe solntse pustyni 8.3                 Shor 8.3
1975 Shiawase no kiiroi hankachi 8.1           Being There 8
1980 Mathe paidi mou grammata 8.4              Sjecas li se, Dolly Bell 8.1
1985 Tajvanska kanasta 8.6                     Kuryer 8.2
1990 Foreign Field, A 8.1                      Ed Wood 8
1995 Strana glukhikh 8.4                       No se lo digas a nadie 8
2000 Eternal Sunshine of the Spotless Mind 8.6 Rat uzivo 8.6
2005 Upside of Anger, The 7.2                  Barfuss 6.9
     [,4]
1915 NA NA
1920 Pollyanna 7.3
1925 Student Prince in Old Heidelberg, The 7.9
1930 Bombshell 7.8
1935 Pygmalion 7.7
1940 Talk of the Town, The 7.6
1945 Tres huastecos, Los 7.8
1950 Miracolo a Milano 7.9
1955 Ensayo de un crimen 8
1960 Buta to gunkan 7.8
1965 Sluzhili dva tovarishcha 8.2
1970 Amarcord 7.9
1975 Garazh 7.8
1980 Valehtelija 8.1
1985 Crimes and Misdemeanors 7.9
1990 Bulto, El 7.9
1995 Being John Malkovich 7.9
2000 Sepet 8.6
2005 Ma quando arrivano le ragazze? 6.5
     [,5]
1915 NA NA
1920 Affairs of Anatol, The 6.7
1925 Circus, The 7.8
1930 Atalante, L' 7.7
1935 Crime de Monsieur Lange, Le 7.6
1940 Claudia 7.5
1945 Letter to Three Wives, A 7.7
1950 Quiet Man, The 7.9
1955 Mister Roberts 8
1960 My Fair Lady 7.8
1965 Spalovac mrtvol 8.1
1970 Charme discret de la bourgeoisie, Le 7.9
1975 Breaking Away 7.7
1980 Kaos 8
1985 Rain Man 7.9
1990 Clerks. 7.9
1995 Secrets & Lies 7.9
2000 Auto da Compadecida, O 8.5
2005 Because of Winn-Dixie 5.9